### ISSUE TITLE
Problem running with figwheel

### ISSUE THREAD

**Issue by mehdisadeghi** [n7a235/phone.app.hive#16]
Running `lein figwheel` in app's root directory and opening the browser at `localhost:3449` leads to this error:

> Figwheel Server: Resource not found

More info: running on archlinux, secrets and google settings file are in place

**Comment by carocad** [comment]
@mehdisadeghi I think the server is not accessible through the web browser since that would be http protocol. I am not sure which protocol do they use for communication but if you run it as per the Cursive setup then you shouldnt care about it since Cursive does the connection handling for you ;) (see PR #10)

**Comment by carocad** [comment]
@mehdisadeghi I am closing this for now. Feel free to reopen it of you have more questions
